apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: prometheus-agi
spec:
  rules:
    - host: demo.prometheus-agi.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-web
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: prometheus-gateway
                port:
                  number: 3001
